### ISSUE TITLE
Revamp Projects Page

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#131]
Current the event page looks like this on `development branch`  

We need some revamp in redesigns and some beautiful content too, to make project page look aesthetic

![image](https://user-images.githubusercontent.com/53480076/94786087-23a44500-03ee-11eb-9e06-c8117b6fdb2a.png)

**Comment by Harshchourasiya** [comment]
Can I Work on this

**Comment by imabp** [comment]
Go Ahead

**Comment by Harshchourasiya** [comment]
> Go Ahead

Hey, **Look** is this correct or I should do more 

**Project Section Before**

![before](https://user-images.githubusercontent.com/48551992/94798971-0f694380-0400-11eb-9a18-e941734e6737.PNG)


![IssusSecond](https://user-images.githubusercontent.com/48551992/94799033-24de6d80-0400-11eb-936c-acf0c0190593.PNG)


**Project Section Now**


![nowProjectDesktop](https://user-images.githubusercontent.com/48551992/94799125-48091d00-0400-11eb-8c41-a8d17d424187.PNG)



![newProjectMobile](https://user-images.githubusercontent.com/48551992/94799137-4c353a80-0400-11eb-8239-8c10d8c2eed6.PNG)




**Problem**

I am not able to change projects names and description  because these are coming from api. I will suggest that change project name with good Manner and also description is too small 


**Can I PR Now**

**Comment by Rihanat** [comment]
Can I still design this

**Comment by Harshchourasiya** [comment]
> Can I still design this

Hey, I am Working on This

**Comment by imabp** [comment]
@Harshchourasiya send PR to development branch

**Comment by imabp** [comment]
I think, you need to check the spelling of **Contribute** in heading
@Harshchourasiya

**Comment by imabp** [comment]
@Rihanat we recommend to see for other issues, or create a new issue if you have any ideas for website

**Comment by imabp** [comment]
Merged #147 into `development` 
Closing this issue.
